stages:
  - test
  - deploy

default:
  image: rust:1.76

test:
  stage: test
  script:
    - cargo test --verbose

compile:
  stage: deploy
  script:
    - cargo build --release --verbose
    - mkdir artifacts
    - cp target/release/csv2ledger .
  artifacts:
    name: $CI_PROJECT_NAME
    paths:
      - csv2ledger
